# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vg' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for vg


  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'



  pod 'RNSound', :path => '../node_modules/react-native-sound'

  target 'vgTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'vg-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for vg-tvOS

  target 'vg-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
